name: CoreSquid
version: '1.0.0'
main: dev.core.squid.CoreSquid
api-version: '1.21'
authors: [ CoreDev ]
description: Professional Squid Game minigame plugin
softdepend: [ Vault ]

commands:
  squid:
    description: Main CoreSquid command
    aliases: [ ]
    usage: /squid <help|join|leave|start|stop|stats|wand|arena|setlobby|setspawn|reload>
    permission: coresquid.use

permissions:
  coresquid.admin:
    description: Full access to CoreSquid
    default: op
  coresquid.use:
    description: Can join games
    default: true
  coresquid.stats:
    description: Can view statistics
    default: true
